
 
df$Airline.Status <- factor(df$Airline.Status)
df$Gender <- factor(df$Gender)
df$Type.of.Travel <- factor(df$Type.of.Travel)
df$Class <- factor(df$Class)
df$Airline.Code <- factor(df$Airline.Code)
df$binarySat <- factor(df$binarySat)

str(df)

#Creating train & test split
set.seed(101)
samplerows <- sample(1:dim(df)[1])
trainrows <- floor(2 * dim(df)[1]/3)
train <- df[samplerows[1:trainrows],]
test <- df[samplerows[(trainrows+1):dim(df)[1]],]

#Loading the library for Decision tree
library(tree)

#Creating our model
tree.model <- tree(binarySat~.,data = train)
#Let's take a look at the model
tree.model
#The significant variables can be found as follows
summary(tree.model)

#Let's plot our Decision Tree
tree.plot <- (plot(tree.model)
text(tree.model, pretty=0))

#Now we make prediction on the test data using our model
tree.pred = predict(tree.model,test,type="class")

#A function to create the confusion matrix using the target variables
#and predictions generated by the model
confusionMatrix <- function(target,prediction){
  confmatrix <- data.frame(target,prediction)
  cm <- table(confmatrix)
  return(cm) 
}

#A function to calculate the error rate from the confusion matrix 
errorRate <- function(cm){
  return(((cm[1,2]+cm[2,1])/sum(cm)))
}

#Let's use the above functions to obtain the confusionMatrix and errorRate
cm <- confusionMatrix(test[,17],tree.pred)
cm

error <- errorRate(cm)
error

cv.tree.model = cv.tree(tree.model, FUN = prune.misclass)
cv.tree.model
plot(cv.tree.model)
